apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    "k8s-app": {{ .Values.app.appLabel }}
spec:
  replicas: {{ .Values.app.replicaCount | default 1 }}
  selector:
    matchLabels:
      "k8s-app": {{ .Values.app.appLabel }}
  template:
    metadata:
      labels:
        "k8s-app": {{ .Values.app.appLabel }}
      name: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Release.Name }}
        
