apiVersion: v1
kind: Service
metadata:
  labels:
    "k8s-app": {{ .Values.appLabel }}
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - nodePort: {{ .Values.service.nodePort }}
      targetPort: {{ .Values.service.port }}
      port: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    "k8s-app": {{ .Values.appLabel }}
